### ISSUE TITLE
Strange behavior on MY ACCOUNT page

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#64]
When logged in with the "windupmicheal" account, if I click on "MY ACCOUNT" at the top-right of the homepage, I am presented with the following page:

<img width="1434" alt="screen shot 2016-11-08 at 15 41 20" src="https://cloud.githubusercontent.com/assets/20033472/20122113/316698b8-a5ca-11e6-9a60-2baf08738685.png">

However, if I login as tackleprotest@gmail.com account, which should have the same membership level credentials, I get the correct account page:

<img width="1440" alt="screen shot 2016-11-08 at 15 59 56" src="https://cloud.githubusercontent.com/assets/20033472/20122428/7216e370-a5cc-11e6-8d93-217dabbcf1b0.png">

**Comment by highwayjourney** [comment]
The issues is resolved.

**Comment by windupmicheal** [comment]
Still seeing the same issue when logged in as my personal account.

Might be worth noting that with my personal account, when I log in, I'm sent back to the front page. When I log in with any of the test accounts, however, I am redirected to the "Recent Posts" page after login.

My personal account is "windupmicheal", and the test accounts include:

tackleprotest@tackletrading.com (pro level membership credentials)
tacklevarsitytest@tackletrading.com (varsity level membership credentials)
tacklerookietest@tackletrading.com (rookie level membership credentials)

**Comment by windupmicheal** [comment]
Correction - Looks like this was never broken to begin with. The reason I saw the page that I saw is because my username "windupmicheal" doesn't have an associated ontraport account. This means that users with ontraport account should all be seeing the my account page.
